import './components/my-element.js'
import './components/name-tag.js'
import './components/more-expressions.js'
import './components/todo-list.js'

import './components/my-lists.js'
import './components/map-directive.js'
import './components/array-method.js'
import './components/array-render.js'
import './components/range-dir.js'
import './components/repeat-dir.JS'
import './components/handling-events.js'
